import { Product } from "./types";

export const PRODUCTS: Product[] = [
  {
    id: "sg-001",
    name: "Aarya Hand-Knit Cotton Pouf",
    category: "poufs",
    price: 89,
    description: "Handcrafted from 100% natural organic cotton, this textured braided pouf serves as an elegant footrest, extra floor seating, or an accent table. Filled with dense, shape-retaining premium beads.",
    image: "https://images.unsplash.com/photo-1581428982868-e410dd047a90?auto=format&fit=crop&w=600&q=80",
    dimensions: "50cm x 50cm x 35cm",
    materials: ["100% Cotton Braid", "EPS Polystyrene Bead filling"],
    careInstructions: "Spot clean with dry cloth or mild fabric cleanser. Rotate periodically to maintain shape.",
    rating: 4.8,
    reviewsCount: 142,
    arAssetScale: 1.0,
  },
  {
    id: "sg-002",
    name: "Jodhpur Jute Braided Stool",
    category: "stools",
    price: 120,
    description: "Constructed with solid hand-turned mango wood legs, this stool features a highly durable, intricately hand-woven natural jute seat. Brings organic warmth and rustic-modern charm to any room.",
    image: "https://images.unsplash.com/photo-1503602642458-232111445657?auto=format&fit=crop&w=600&q=80",
    dimensions: "40cm x 40cm x 45cm",
    materials: ["Solid Mango Wood", "Natural Jute Fiber"],
    careInstructions: "Vacuum regularly. Wipe wooden legs with a slightly damp cloth.",
    rating: 4.9,
    reviewsCount: 88,
    arAssetScale: 1.1,
  },
  {
    id: "sg-003",
    name: "Amara Indigo Embroidered Cushion",
    category: "cushions",
    price: 45,
    description: "An absolute masterpiece of traditional Indian craftsmanship. Hand-embroidered with dynamic indigo thread patterns, this heavy cotton canvas pillow features elegant piped edges and a hidden heavy-duty zipper.",
    image: "https://images.unsplash.com/photo-1583847268964-b28dc8f51f92?auto=format&fit=crop&w=600&q=80",
    dimensions: "45cm x 45cm",
    materials: ["100% Cotton Canvas", "Pure Linen Backing", "Hypoallergenic Poly-fill Insert"],
    careInstructions: "Dry clean recommended. Iron on low heat on the reverse side.",
    rating: 4.7,
    reviewsCount: 204,
    arAssetScale: 0.85,
  },
  {
    id: "sg-004",
    name: "Loom-Woven Woolen Floor Pouf",
    category: "poufs",
    price: 149,
    description: "A substantial floor pouf woven with heavy-gauge, multi-toned wool yarns. Featuring geometric nomadic patterns, this high-density filled pouf delivers ultimate comfort and acts as a bold structural highlight.",
    image: "https://images.unsplash.com/photo-1600121848594-d8644e57abab?auto=format&fit=crop&w=600&q=80",
    dimensions: "60cm x 60cm x 40cm",
    materials: ["80% Merino Wool", "20% Cotton", "High-density foam & cotton batting filling"],
    careInstructions: "Vacuum clean with upholstery brush. Professional clean only for persistent spills.",
    rating: 4.9,
    reviewsCount: 61,
    arAssetScale: 1.25,
  },
  {
    id: "sg-005",
    name: "Modular Linen Cloud Sofa Unit",
    category: "sofas",
    price: 499,
    description: "Experience lounge perfection with this modular cloud unit. Fully upholstered in heavy, breathable Belgian-style flax linen with down-alternative double layering. Can be configured into corner or mid-row seating.",
    image: "https://images.unsplash.com/photo-1555041469-a586c61ea9bc?auto=format&fit=crop&w=600&q=80",
    dimensions: "95cm x 95cm x 68cm",
    materials: ["100% Organic Flax Linen", "Sinuous Spring Support", "Down-Alternative Memory Wrap"],
    careInstructions: "Removable cushion covers are machine washable on delicate cycle. Fluff pillows regularly.",
    rating: 5.0,
    reviewsCount: 37,
    arAssetScale: 1.8,
  },
  {
    id: "sg-006",
    name: "Nomad Textured Kilim Cushion",
    category: "cushions",
    price: 55,
    description: "Featuring a flat-woven Kilim design, this cushion showcases rich organic tones inspired by the Thar Desert. Handloomed with a high-texture wool face and a solid washed-cotton canvas back.",
    image: "https://images.unsplash.com/photo-1518156677180-95a2893f3e9f?auto=format&fit=crop&w=600&q=80",
    dimensions: "50cm x 50cm",
    materials: ["60% Wool", "40% Cotton", "Duck Down Feather Insert"],
    careInstructions: "Dry clean only. Gentle spot brushing to lift dust particles.",
    rating: 4.6,
    reviewsCount: 112,
    arAssetScale: 0.9,
  },
  {
    id: "sg-007",
    name: "Kashmir Merino Herringbone Throw",
    category: "throws",
    price: 110,
    description: "An incredibly soft, tissue-weight throw woven in a classic micro-herringbone weave. Made of fine wool loomed in Kashmir, finished with delicate hand-twisted fringe details. Drapes elegantly over sofas or beds.",
    image: "https://images.unsplash.com/photo-1543294001-f7cbfe92237e?auto=format&fit=crop&w=600&q=80",
    dimensions: "130cm x 180cm",
    materials: ["100% Kashmir Merino Wool"],
    careInstructions: "Dry clean or hand wash in cold water with mild wool wash. Lay flat to dry.",
    rating: 4.9,
    reviewsCount: 153,
    arAssetScale: 0.8,
  },
  {
    id: "sg-008",
    name: "Thar Woven Accent Stool",
    category: "stools",
    price: 135,
    description: "A gorgeous conversation piece. This low-profile stool features an incredibly intricate, cross-woven geometric webbing of organic canvas cords, supported by a masterfully detailed matte-black solid steel base.",
    image: "https://images.unsplash.com/photo-1592078615290-033ee584e267?auto=format&fit=crop&w=600&q=80",
    dimensions: "45cm x 45cm x 38cm",
    materials: ["Organic Cotton Canvas Cord", "Solid Carbon Steel Frame"],
    careInstructions: "Spot clean canvas rope with a light damp cloth and soap foam. Avoid soaking.",
    rating: 4.8,
    reviewsCount: 45,
    arAssetScale: 1.0,
  },
  {
    id: "sg-009",
    name: "Aarya Hand-Woven Dhurrie Area Rug",
    category: "rugs",
    price: 245,
    description: "An authentic, heavy-weight flat-woven cotton dhurrie rug featuring elegant tribal geometric motifs and subtle natural fringe. Woven entirely by hand on traditional horizontal looms.",
    image: "https://images.unsplash.com/photo-1576013551627-0cc20b96c2a7?auto=format&fit=crop&w=600&q=80",
    dimensions: "200cm x 140cm",
    materials: ["100% Organic Hand-spun Cotton"],
    careInstructions: "Vacuum regularly without beater bar. Spot clean spills immediately with mild soapy water.",
    rating: 4.9,
    reviewsCount: 76,
    arAssetScale: 1.5,
  },
  {
    id: "sg-010",
    name: "Elysian Bouclé Swivel Armchair",
    category: "chairs",
    price: 380,
    description: "Indulge in cozy sophistication. This accent armchair features a masterfully curved silhouette fully upholstered in luxurious, high-texture cream bouclé. Equipped with a hidden, heavy-duty 360-degree swivel mechanism.",
    image: "https://images.unsplash.com/photo-1567538096630-e0c55bd6374c?auto=format&fit=crop&w=600&q=80",
    dimensions: "70cm x 70cm x 75cm",
    materials: ["High-texture Cream Bouclé Fabric", "Solid Hardwood Inner Frame", "Swivel Steel Base"],
    careInstructions: "Professional upholstery cleaning recommended. Vacuum with soft brush attachment.",
    rating: 5.0,
    reviewsCount: 29,
    arAssetScale: 1.2,
  },
  {
    id: "sg-011",
    name: "Desert Bloom Velvet Bolster Cushion",
    category: "cushions",
    price: 49,
    description: "Add an elegant architectural accent to your seating arrangement. This bolster pillow is encased in ultra-soft, heavy-weight cotton velvet with a rich warm terracotta hue, complete with classic piping and tufted button ends.",
    image: "https://images.unsplash.com/photo-1584100936595-c0654b55a2e2?auto=format&fit=crop&w=600&q=80",
    dimensions: "55cm x 20cm x 20cm",
    materials: ["Premium Cotton Velvet", "Hypoallergenic Polyester Fiberfill Insert"],
    careInstructions: "Dry clean only. Velvet pile can be gently steamed to restore loft.",
    rating: 4.8,
    reviewsCount: 34,
    arAssetScale: 0.9,
  }
];

export const MOCK_REVIEWS = [
  {
    id: "r-1",
    author: "Elena Rostova",
    rating: 5,
    text: "The Aarya pouf is simply exquisite! The braid is incredibly thick and firm, it doesn't sag at all when sitting. The texture feels extremely high end. Matches my Nordic living room perfectly.",
    date: "May 14, 2026",
  },
  {
    id: "r-2",
    author: "Marc Dupont",
    rating: 5,
    text: "I bought the modular linen cloud sofa and two jute stools for my apartment in Paris. They arrived in flawless condition. The craftsmanship is outstanding, easily matching or exceeding high-end Italian design stores.",
    date: "June 2, 2026",
  },
  {
    id: "r-3",
    author: "Aarav Sharma",
    rating: 4,
    text: "The embroidery on the Amara Indigo cushion is genuine handloom level. It has slight gorgeous irregularities that show true handcrafting. Fantastic quality, proud to support local Indian exporters.",
    date: "June 20, 2026",
  }
];
